version: '3'

services:       
  web:
    build: .
    command: npm run start
    env_file:
      - .env
    ports:
      - ${FRONTEND_NODE_PORT}:3000
    restart: always

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    ports:
      - ${FRONTEND_NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
