version: '3'

services:
  env_file:
   - ./.env
  environment:
  - FRONTEND_NODE_PORT=${FRONTEND_NODE_PORT}        
  - FRONTEND_NGINX_PORT=${FRONTEND_NGINX_PORT}        
  web:
    build: .
    command: npm run start
    ports:
      - ${FRONTEND_NODE_PORT}:3000
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - ${FRONTEND_NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
