version: "3"
services:
  node-nginx-jenkins:
    container_name: Node-nginx-jenkins
    image: node-nginx-jenkins
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:3000
